export { default as Article } from './article/Article'
export { default as Brand } from './brand/Brand'
export { default as CTA } from './cta/Cta'
export { default as Feature } from './feature/Feature'
export { default as NavBar } from './navBar/NavBar'
// New
export { default as SideBar } from './sideBar/SideBar'
export { default as Home } from './home/Home'
export { default as Resume } from './resume/Resume'
export { default as About } from './about/About'
export { default as Portfolio } from './portfolio/Portfolio'
export { default as Blog } from './blog/Blog'
export { default as Contact } from './contact/Contact'